name: flutter_local_databases
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # sqlfite
  sqflite: ^2.1.0

  # path provider
  path_provider: ^2.0.11

  # shared preferences
  shared_preferences: ^2.0.15

  # icons
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/man_avatar.png
    - assets/images/woman_avatar.png

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto-Bold.ttf